controller:
  serviceType: LoadBalancer
  serviceAnnotations:
    cloud.google.com/load-balancer-type: "External"

  nodeSelector:
    role: jenkins

  serviceAccountName: jenkins-ksa

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - docker-workflow:latest
    - google-oauth-plugin:latest
    - pipeline-stage-view:latest
    - blueocean:latest
    - github:latest

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

  javaOpts: "-Xmx1500m"

persistence:
  enabled: true
  size: 10Gi

agent:
  enabled: true
  namespace: default
  nodeSelector:
    role: jenkins
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
